### ISSUE TITLE
Website freezes when a big file is sent 

### ISSUE THREAD

**Issue by sajal-chuttani** [sajal-chuttani/BlueSock#1]
big files are discarded once they are loaded in the server better thing to do will be to discard big files while on the machine by **js**

**Comment by sajal-chuttani** [comment]
Correct the spelling mistake on the download file page

**Comment by sajal-chuttani** [comment]
Add bootstrap to the working of webapp (completely forgot it)

**Comment by sajal-chuttani** [comment]
and for some reason the web browser freezes too

**Comment by brandon-wallace** [comment]
#6 Created a pull request to resolve this issue in branch limit-file-size.

**Comment by sajal-chuttani** [comment]
#6 checking something  just a test

**Comment by sajal-chuttani** [comment]
#6 fix : another ets

**Comment by brandon-wallace** [comment]
I have adjusted the code so that the total file size in checked before writing to the database.

**Comment by sajal-chuttani** [comment]
issue resolved by #6
