### ISSUE TITLE
Grammar Errors

### ISSUE THREAD

**Issue by bld-sync** [sajal-chuttani/BlueSock#4]
**On the home page:**
Your 'email me' doesn't open a email, or copy your email to your clipboard

**On the success page:**
Your files are successfully uploaded to the server! Please make sure to take a note of the below credentials
or else nobody will be able to access shared files

**On the get page:**
Your files will be deleted from our database once you download them on your machine

**Comment by sajal-chuttani** [comment]
evidently, the 'email me' link works on my machine 
fix: adding my email along with the link
